tap "homebrew/cask-fonts"
cask "font-jetbrains-mono-nerd-font"
tap "coursier/formulas"
brew "coursier"
cask "firefox"

brew "neovim"
brew "tmux"
brew "fnm"
brew "fzf"
brew "zoxide"
brew "nnn"
brew "zsh"
brew "yabai"
brew "starship"
brew "exa"
