export PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
eval "$(/opt/homebrew/bin/brew shellenv)"

# Vi mode
source $(brew --prefix)/opt/zsh-vi-mode/share/zsh-vi-mode/zsh-vi-mode.plugin.zsh

# History
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=$HISTSIZE
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt SHARE_HISTORY

export VISUAL=nvim
export EDITOR=nvim
export ZVM_VI_EDITOR=nvim

alias ls="exa"
alias utcdate='date -u +"%Y-%m-%dT%H:%M:%SZ"'

# # Feed the output of fd into fzf
# fd --type f | fzf

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git --color=always'
export FZF_DEFAULT_OPTS="--ansi"

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# install zoxide
eval "$(zoxide init zsh)"

autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '%b '
setopt PROMPT_SUBST
PROMPT='%F{yellow}%*%f %F{reset}$(basename $PWD)%f %F{green}${vcs_info_msg_0_}%F{reset}'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/lcolli/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/lcolli/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# opam configuration
[[ ! -r /Users/lcolli/.opam/opam-init/init.zsh ]] || source /Users/lcolli/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null


current_branch () {
  echo $(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
}
